---
- name: Allow specific IP address and port on fortios
  hosts: fortigates
  gather_facts: false
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
  tasks:

    - name: Create Address
      fortios_firewall_address:
        state: present
        firewall_address:
          name: webservers
          associated_interface: port2
          subnet: 10.0.2.0 255.255.255.0


    - name: Create Address
      fortios_firewall_address:
        state: present
        firewall_address:
          name: external
          associated_interface: port3
          subnet: 10.0.3.0 255.255.255.0
           
    - name: Create Web policy
      fortios_firewall_policy:
        vdom: "root"
        state: "present"
        firewall_policy:
          name: "webpolicy"
          policyid: "1"
          action: accept
          srcintf:
            - name: "port3"
          dstintf:
            - name: "port2"
          srcaddr: 
            - name: "external"
          dstaddr:
            - name: "webservers"
          service: 
            - name: "HTTP"
            - name: "HTTPS"
          schedule: "always"

    - name: Create Remote Access Policy
      fortios_firewall_policy:
        vdom: "root"
        state: "present"
        firewall_policy:
          name: "remote-access"
          policyid: "2"
          action: accept
          srcintf:
            - name: "port3"
          dstintf:
            - name: "port2"
          srcaddr: 
            - name: "external"
          dstaddr:
            - name: "webservers"
          service: 
            - name: "SSH"
          schedule: "always"
