---
- name: Blocks specific IP address on fortios
  hosts: "{{ target_fortigate }}"
  vars:
    fortigate_host: "{{ fg_host }}"
    fortigate_username: "{{ fg_user }}"
    fortigate_password: "{{ fg_password }}"
    block_ip: "{{ block_ip_address }}"
  tasks:
    - name: Block IP Address
      fortios_firewall_policy:
        host: "{{ fortigate_host }}"
        username: "{{ fortigate_username }}"
        password: "{{ fortigate_password }}"
        state: "present"
        firewall_policy:
          srcaddr: "{{ block_ip }}"
          action: "deny"
