---
- name: Create API User
  hosts: fortigates
  gather_facts: false
  collections:
    - fortinet.fortios

  tasks:
  - name: Configure local users.
    fortios_user_local:
      vdom: root
      state: "present"
      user_local:
        name: "{{ item.name }}"
        #auth_concurrent_override: "enable"
        #auth_concurrent_value: "0"
        #authtimeout: "0"
        email_to: "{{ item.email }}"
        #fortitoken: "<your_own_value> (source user.fortitoken.serial-number)"
        #id:  "8"
        passwd: "{{ item.passwd }}"
        #passwd_policy: "<your_own_value> (source user.password-policy.name)"
        #passwd_time: "<your_own_value>"
        #ppk_identity: "<your_own_value>"
        #ppk_secret: "<your_own_value>"
        #radius_server: "<your_own_value> (source user.radius.name)"
        #sms_custom_server: "<your_own_value> (source system.sms-server.name)"
        #sms_phone: "<your_own_value>"
        #sms_server: "fortiguard"
        status: "enable"
        #tacacs_plus_server: "<your_own_value> (source user.tacacs+.name)"
        two_factor: "disable"
        #two_factor_authentication: "fortitoken"
        #two_factor_notification: "email"
        type: "password"
        username_case_sensitivity: "disable"
        #username_sensitivity: "disable"
        #workstation: "<your_own_value>"
    loop: "{{ fortios_users }}"
