---
- name: Get Fortinet Fortigate firewall_policy facts
  gather_facts: false
  hosts: fortigates
  collections:
    - fortinet.fortios

  tasks:

  - name: use fortios_configuration_fact module to get firewall_policy facts
    fortios_configuration_fact:
      vdom: "root"
      #access_token: "{{ token }}"
      selectors:
      - selector: firewall_policy
    register: forti_firewallpolicy
  
  - name: debug forti_firewallpolicy
    ansible.builtin.debug:
      msg: "{{ forti_firewallpolicy.meta[0].results | to_nice_yaml }}"
      verbosity: 2
    delegate_to: localhost

  - name: set fact
    ansible.builtin.set_fact:
      firewall_policy: "{{ forti_firewallpolicy.meta[0].results }}"
      #firewall_policy: "{{ forti_firewallpolicy.meta[0].results | to_nice_yaml }}"
      verbosity: 2
    delegate_to: localhost

  - name: debug firewall_policy
    ansible.builtin.debug:
      var: firewall_policy
      verbosity: 2
    delegate_to: localhost

  - name: Write out the policy to host_vars
    ansible.builtin.template:
      src: ./firewall_policy.j2
      dest: "./host_vars/{{ inventory_hostname }}.yml" 
    delegate_to: localhost
