---
- name: Upload New Certificate to FortiWeb
  hosts: fortiweb
  gather_facts: false
  collections:
    - fortinet.fortiweb
  vars:

  tasks:

    - name: Upload pkcs12 certificate 
      fwebos_certificate_local_import_certificate:
       action: add
       vdom: root
       type: PKCS12Certificate
       certificateWithKeyFile: ./files/aaphub.p12
       password: PASSW0RD
