---
- name: Create Virtual IP
  hosts: fortiweb
  gather_facts: false
  collections:
  - fortinet.fortiweb
  vars:

  tasks:

  - name: Create virtual IP
    fwebos_virtual_ip:
      action: add
      name: "{{ fwebos_vip_name }}"
      vip: "{{ vip_ip }}"
      interface: "port1"
      vdom: root
...
