---
- name: Create Server Pool
  hosts: fortiweb
  gather_facts: false
  collections:
  - fortinet.fortiweb
  vars:
    ansible_network_os: fortinet.fortiweb.fwebos
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
  tasks:
  - name: Create server pool 
    fwebos_server_pool:
      action: add 
      vdom: root
      name: "{{ fwebos_virtual_server | replace('.','_') }}_pool"
      type: reverse-proxy
      server_balance: disable
      #server_balance: enable
      lb_algo: round-robin
      comment: test111
      # health: HLTHCK_ICMP
      # persistence: test
      # reuse_conn_total_time: 100
      # reuse_conn_max_request: 100
      # reuse_conn_max_count: 100

  # - name: edit server pool
  #   fwebos_server_pool:
  #    action: edit 
  #    vdom: root
  #    name: test
  #    type: reverse-proxy
  #    server_balance: enable
  #    lb_algo: round-robin
  #    comment: test111
  #    health: HLTHCK_ICMP
  #    persistence: test
  #    reuse_conn_total_time: 100
  #    reuse_conn_idle_time: 20
  #    reuse_conn_max_request: 100
  #    reuse_conn_max_count: 100
  #
  # - name: delete server pool 
  #   fwebos_server_pool:
  #     action: delete 
  #     vdom: root
  #     name: test 