---
- name: Create Virtual IP
  hosts: fortiweb
  gather_facts: false
  collections:
  - fortinet.fortiweb
  vars:

  tasks:
  - name: Set VIP Name variable
    ansible.builtin.set_fact:
      vip_name: "{{ fwebos_virtual_server_name }}_vip"

  - name: Create virtual IP
    fwebos_virtual_ip:
      action: add
      name: "{{ vip_name }}"
      vip: "{{ vip_ip }}"
      interface: "port1"
      vdom: root

  - name: Set variables for workflow
    ansible.builtin.set_stats:
      data:
        vip_name: "{{ vip_name }}"
...
