---
- name:  Create New Certificatei Request in FortiWeb
  hosts: fortiweb
  gather_facts: false
  collections:
    - fortinet.fortiweb
  vars:
    ansible_network_os: fortinet.fortiweb.fwebos
    ansible_connection: ansible.netcommon.httpapi
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443

  tasks:
  - name: Create certificate csr 
    fwebos_certificate_local_csr:
      action: add 
      name: host2.entrenchedrealist.com 
      vdom: root
      idType: hostIp
      alt_name_type: 2
      ip: 5.5.5.5
      keySize: 2048
      enrollmentMethod: file
      organization: Red Hat, Inc.
      localityCity: Pasadena
      stateProvince: MD
      countryRegion: US
      email: truch@redhat.com
      organizationUnit_1: orgunit
      alt_name_type_1: 2
      alt_name_text_1: host2.entrenchedrealist.com
    register: csr_result

  - name: Debug out
    debug:
      msg: "{{ csr_result }}"

#    - name: Create certificate csr 
#      fwebos_certificate_local_csr:
#       action: add 
#       vdom: root1
#       idType: hostIp
#       alt_name_type: 2
#       ip: 0.0.0.0
#       keySize: 1024
#       enrollmentMethod: file
#       name: test_1 
#       organization: org
#       localityCity: city1
#       stateProvince: state1
#       countryRegion: US
#       email: test@test.com
#       organizationUnit_1: orgunit
#       alt_name_type_1: 2
#       alt_name_text_1: aaaaaa.com
#
#    - name: delete certificate csr 
#      fwebos_certificate_local_csr:
#       action: delete 
#       vdom: root1
#       name: test_1
#
#    - name: Create certificate csr 
#      fwebos_certificate_local_csr:
#       action: add 
#       vdom: root1
#       idType: email
#       subjectEmail: test@gmail.com
#       alt_name_type: 2
#       ip: 0.0.0.0
#       keySize: 1024
#       enrollmentMethod: file
#       name: test_2 
#       organization: org
#       localityCity: city1
#       stateProvince: state1
#       countryRegion: US
#       email: test@test.com
#       organizationUnit_1: orgunit
